### ISSUE TITLE
Panic while creating new contact

### ISSUE THREAD

**Issue by muesli** [katzenpost/catshadow#25]
panic: <memcall> could not acquire lock on 0x7fa0ef4f3000, limit reached? [Err: cannot allocate memory]

goroutine 60 [running]:
github.com/awnumar/memguard/core.Panic(0xdbb260, 0xc000089f00)
        github.com/awnumar/memguard@v0.22.2/core/exit.go:86 +0x3d
github.com/awnumar/memguard/core.NewBuffer(0x20, 0xc000089ee0, 0x0, 0x0)
        github.com/awnumar/memguard@v0.22.2/core/buffer.go:75 +0x34f
github.com/awnumar/memguard.NewBuffer(0x20, 0xc000089ee0)
        github.com/awnumar/memguard@v0.22.2/buffer.go:47 +0x2f
github.com/katzenpost/doubleratchet.InitRatchet(0xfe4040, 0xc000010038, 0xc0006e7b80, 0xc000613ba8, 0xa6c432)
        github.com/katzenpost/doubleratchet@v0.0.5/ratchet.go:204 +0x3aa
github.com/katzenpost/catshadow.NewContact(0xc0001935e6, 0x5, 0x244f15244679b2e6, 0xc000149300, 0xc000172000, 0x0, 0x3, 0x3)
        github.com/katzenpost/catshadow@v0.0.14/contact.go:103 +0x3d
github.com/katzenpost/catshadow.(*Client).createContact(0xc000162c30, 0xc0001935e6, 0x5, 0xc0001935f0, 0x6, 0x8, 0x1, 0x0)
        github.com/katzenpost/catshadow@v0.0.14/client.go:257 +0xd1
github.com/katzenpost/catshadow.(*Client).worker(0xc000162c30)
        github.com/katzenpost/catshadow@v0.0.14/worker.go:83 +0x4b9
github.com/katzenpost/core/worker.(*Worker).Go.func1(0xc000162c30, 0xc0003d6440)
        github.com/katzenpost/core@v0.0.11/worker/worker.go:39 +0x51
created by github.com/katzenpost/core/worker.(*Worker).Go
        github.com/katzenpost/core@v0.0.11/worker/worker.go:37 +0x86

**Comment by mixmasala** [comment]
could you please attach the debug log output (before the panic).
I believe you mentioned on IRC that this is on archlinux with kernel 5.10.x

This issue looks like it might be similar:
https://github.com/awnumar/memguard/issues/13

Can you provide the output of ulimit -l ?

on debian testing I see:
user@katz:~$ ulimit -l
503897

And I think that might be why this fails.

**Comment by mixmasala** [comment]
could you please attach the debug log output (before the panic).
I believe you mentioned on IRC that this is on archlinux with kernel 5.10.x

This issue looks like it might be similar:
https://github.com/awnumar/memguard/issues/13

Can you provide the output of ulimit -l ?

on debian testing I see:
user@katz:~$ ulimit -l
503897

And I think that might be why this fails.

**Comment by david415** [comment]
@muesli please, can you post your "ulimit -a" output into this ticket?

**Comment by muesli** [comment]
@mixmasala 

```bash
$ ulimit -l
64
```

**Comment by muesli** [comment]
@david415 

```
real-time non-blocking time  (microseconds, -R) unlimited
core file size              (blocks, -c) unlimited
data seg size               (kbytes, -d) unlimited
scheduling priority                 (-e) 0
file size                   (blocks, -f) unlimited
pending signals                     (-i) 256849
max locked memory           (kbytes, -l) 64
max memory size             (kbytes, -m) unlimited
open files                          (-n) 1024
pipe size                (512 bytes, -p) 8
POSIX message queues         (bytes, -q) 819200
real-time priority                  (-r) 0
stack size                  (kbytes, -s) 8192
cpu time                   (seconds, -t) unlimited
max user processes                  (-u) 256849
virtual memory              (kbytes, -v) unlimited
file locks                          (-x) unlimited
```

**Comment by mixmasala** [comment]
on debian buster I checked what the default is
```
$ ulimit -l
65536
```
I tested catchat with that value and it works.
I hunted around to see if I could find out what the default archlinux /etc/security/limits.conf are set to but all I could find was this forum post and some possibly related tickets

https://bbs.archlinux.org/viewtopic.php?id=243648
https://github.com/systemd/systemd/issues/11386

I can recreate the crash, i.e.
```
user@katz:~/catchats/blah$ ulimit -l 64
user@katz:~/catchats/blah$ ulimit -l
64
user@katz:~/catchats/blah$ catchat -f config.toml
Katzenpost is still pre-alpha.  DO NOT DEPEND ON IT FOR STRONG SECURITY OR ANONYMITY.
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
Enter statefile decryption passphrase:
08:27:46.760 DEBU pki/voting/Client: Get(ctx, 96304)
QSGTextureAtlas: texture atlas allocation failed, code=501
08:28:02.246 NOTI pki/voting/Client: OK, received fully signed consensus document.
registering client with mixnet Provider
panic: <memcall> could not acquire lock on 0x7fc560014000, limit reached? [Err: cannot allocate memory]

goroutine 7 [running]:
github.com/awnumar/memguard/core.Panic(0xdd62c0, 0xc0001ec4f0)
        github.com/awnumar/memguard@v0.22.2/core/exit.go:86 +0x3d
github.com/awnumar/memguard/core.NewBuffer(0x20, 0xc0001ec4d0, 0x0, 0x0)
        github.com/awnumar/memguard@v0.22.2/core/buffer.go:75 +0x34f
github.com/awnumar/memguard.NewBuffer(0x20, 0xc0001ec4d0)
        github.com/awnumar/memguard@v0.22.2/buffer.go:47 +0x2f
github.com/katzenpost/doubleratchet.InitRatchet(0x1004f80, 0xc000010038, 0x7fc5599340b8, 0xc0000d7648, 0x557dc9)
        github.com/katzenpost/doubleratchet@v0.0.8/ratchet.go:225 +0x3aa
```

So I think you should raise the limits for memlock and see if that works for you on Arch.

**Comment by mixmasala** [comment]
This crash can also be triggered with the doubleratchet unit tests
```
user@katz:~/go/src/github.com/katzenpost/doubleratchet$ go test
OK: 9 passed
PASS
ok  	github.com/katzenpost/doubleratchet	0.189s
user@katz:~/go/src/github.com/katzenpost/doubleratchet$ ulimit -l 8096
user@katz:~/go/src/github.com/katzenpost/doubleratchet$ go test

----------------------------------------------------------------------
PANIC: ratchet_test.go:93: DoubleRatchetSuite.Test_RealKeyExchange

... Panic: <memcall> could not acquire lock on 0x7f5f4967a000, limit reached? [Err: cannot allocate memory] (PC=0x436B58)
```
So I was surprised to see that doubleratchet is locking such a large amount of memory and I am looking to see if I can find out what is going on there.

**Comment by mixmasala** [comment]
https://github.com/katzenpost/doubleratchet/tree/add_memguard_tests

I noticed that if I set
```ulimit -l 16```

Then the test will fail like so:
```
user@katz:~/go/src/github.com/katzenpost/doubleratchet$ ulimit -l
16
user@katz:~/go/src/github.com/katzenpost/doubleratchet$ go test -v -run TestMemGuardUlimit
=== RUN   TestMemGuardUlimit
    memguard_test.go:18: locking 1 kb
    memguard_test.go:23: locked 1024
    memguard_test.go:18: locking 2 kb
    memguard_test.go:23: locked 2048
    memguard_test.go:18: locking 3 kb
    memguard_test.go:23: locked 3072
    memguard_test.go:18: locking 4 kb
    memguard_test.go:23: locked 4096
    memguard_test.go:18: locking 5 kb
--- FAIL: TestMemGuardUlimit (0.00s)
panic: <memcall> could not acquire lock on 0x7ffa85e20000, limit reached? [Err: cannot allocate memory] [recovered]
	panic: <memcall> could not acquire lock on 0x7ffa85e20000, limit reached? [Err: cannot allocate memory]

goroutine 19 [running]:
testing.tRunner.func1.1(0x633680, 0xc000082960)
	/usr/lib/go-1.15/src/testing/testing.go:1072 +0x30d
testing.tRunner.func1(0xc00009c480)
	/usr/lib/go-1.15/src/testing/testing.go:1075 +0x41a
panic(0x633680, 0xc000082960)
	/usr/lib/go-1.15/src/runtime/panic.go:969 +0x1b9
github.com/awnumar/memguard/core.Panic(0x633680, 0xc000082960)
	/home/user/go/pkg/mod/github.com/awnumar/memguard@v0.22.2/core/exit.go:86 +0x3d
github.com/awnumar/memguard/core.NewBuffer(0x1400, 0x0, 0x0, 0x0)
	/home/user/go/pkg/mod/github.com/awnumar/memguard@v0.22.2/core/buffer.go:75 +0x34f
github.com/awnumar/memguard.NewBuffer(0x1400, 0xc000096240)
	/home/user/go/pkg/mod/github.com/awnumar/memguard@v0.22.2/buffer.go:47 +0x2f
github.com/awnumar/memguard.NewBufferFromReader(0x6b5bc0, 0x829120, 0x1400, 0xc00008ff60, 0x1, 0x1)
	/home/user/go/pkg/mod/github.com/awnumar/memguard@v0.22.2/buffer.go:83 +0x45
github.com/katzenpost/doubleratchet.TestMemGuardUlimit(0xc00009c480)
	/home/user/go/src/github.com/katzenpost/doubleratchet/memguard_test.go:19 +0x166
testing.tRunner(0xc00009c480, 0x67f418)
	/usr/lib/go-1.15/src/testing/testing.go:1123 +0xef
created by testing.(*T).Run
	/usr/lib/go-1.15/src/testing/testing.go:1168 +0x2b3
exit status 2
FAIL	github.com/katzenpost/doubleratchet	0.009s
```

**Comment by muesli** [comment]
Thank you, that sounds promising. I will try this out right now.

**Comment by david415** [comment]
@muesli I think maybe the fix might be to first run ulimit -l 65536

**Comment by mixmasala** [comment]
yes, you can edit /etc/security/limits.conf or just ulimits -l blah... however i think you can LOWER limits but not raise them, so you may need to edit the system limits first.

16 kb sounds pretty low but i haven't figured out why doubleratchet needs more than that yet. I think there could be a memory leak with discarding memguard.LockedBuffers that we haven't noticed due to higher limits but it is strange because our keys and stuff are pretty small so even 16KB is pretty big relative to that. I did notice that if you have ulimit -l 16; instantiating a memguard LockedBuffer will fail at somewhere between 4-5 kb so there is obviously some over head (maybe a page boundary?)

**Comment by mixmasala** [comment]
It looks like docker creates containers with a default ulimit 16 as well

**Comment by mixmasala** [comment]
https://github.com/awnumar/memguard/blob/a5d41f2843eedfedf31d0f8e6468cc95879fbaf5/core/buffer.go#L57
https://github.com/awnumar/memguard/blob/master/buffer.go#L16

thanks to @claucece for pointing this out.

as the memguard descriptions says:

```Buffers that store plaintext data are fortified with guard pages and canary values to detect spurious accesses and overflows.```
(a page allocation on linux is like 4KB so per buffer is going to use, I think, about 12KB sans any optimizations)
well, we use quite a few of these buffers per ratchet so I dont think we'll avoid exceeding 16KB no matter what we do.
