### ISSUE TITLE
Crash trying to add a new contact

### ISSUE THREAD

**Issue by muesli** [katzenpost/catshadow#26]
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xa93280]

goroutine 148 [running]:
github.com/katzenpost/memspool/client.(*SpoolReadDescriptor).GetWriteDescriptor(...)
        github.com/katzenpost/memspool@v0.0.14/client/client.go:66
github.com/katzenpost/catshadow.NewContact(0xc000522b78, 0x4, 0x8bbace37533a1a22, 0x0, 0xc0000f0000, 0xc000306600, 0xc000259eb8, 0xc0002004e0)
        github.com/katzenpost/catshadow@v0.0.32/contact.go:133 +0xa0
github.com/katzenpost/catshadow.(*Client).createContact(0xc00025e000, 0xc000522b78, 0x4, 0xc000522b80, 0x8, 0x8, 0x1, 0x0)
        github.com/katzenpost/catshadow@v0.0.32/client.go:327 +0xd1
github.com/katzenpost/catshadow.(*Client).worker(0xc00025e000)
        github.com/katzenpost/catshadow@v0.0.32/worker.go:86 +0x539
github.com/katzenpost/core/worker.(*Worker).Go.func1(0xc00025e000, 0xc000316020)
        github.com/katzenpost/core@v0.0.12/worker/worker.go:39 +0x51
created by github.com/katzenpost/core/worker.(*Worker).Go
        github.com/katzenpost/core@v0.0.12/worker/worker.go:37 +0x86
```

**Comment by mixmasala** [comment]
I am aware of a race between the client bootstrapping and the 'add contact' function in the Qt UX - I wasn't sure how to fix this but basically you need to wait for the client to bootstrap and create the remote spool before clicking add contact. The indicator in the top title bar should display 'connected' before you try and add a contact.

**Comment by mixmasala** [comment]
I was hoping that you could see why the Add Contact functionality can be called before the client is bootstrapped.

**Comment by mixmasala** [comment]
the isConnected flag seemed to be correctly indicating the status of the backend but I was able to click add contact before the connected state is reached and then the client does crash

**Comment by muesli** [comment]
It's your lucky day: https://github.com/katzenpost/catchat/pull/22

The backend should still be separately protected against that panic, of course.

I'd also like to note that I'm fairly certain that I was already connected at the point when I triggered the crash.
